version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app_data:/app/app_data
    command: uvicorn app.presentation:app --host 0.0.0.0 --port 8000 --env-file /app/.env
